version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: containers/app/Dockerfile
    volumes:
      - ".:/usr/src/vuttr"
    ports:
      - "8080:8080"
    expose:
      - 8080
  json-server:
    build: containers/json-server
    volumes:
      - "./containers/json-server:/usr/src/json-server"
    ports:
      - "3000:3000"
    expose:
      - 3000
